### PR TITLE
feat: upgrade to Angular 17

### PR DESCRIPTION
**Pull request by arturovt**

### CODE REVIEW

**Comment by Wushurui** [comment]
I got this error after I use the ng17 branch in my package.json:
An unhandled exception occurred: Cannot find module 'single-spa-angular/libs/single-spa-angular/webpack'
Require stack:
- /Users/alexawu/Documents/upgrade-projects/hk-aws-agt-rpt-admin-sws/extra-webpack.config.js
- /Users/alexawu/Documents/upgrade-projects/hk-aws-agt-rpt-admin-sws/node_modules/@angular-builders/custom-webpack/dist/utils.js
- /Users/alexawu/Documents/upgrade-projects/hk-aws-agt-rpt-admin-sws/node_modules/@angular-builders/custom-webpack/dist/custom-webpack-builder.js
- /Users/alexawu/Documents/upgrade-projects/hk-aws-agt-rpt-admin-sws/node_modules/@angular-builders/custom-webpack/dist/transform-factories.js
- /Users/alexawu/Documents/upgrade-projects/hk-aws-agt-rpt-admin-sws/node_modules/@angular-builders/custom-webpack/dist/generic-browser-builder.js
- /Users/alexawu/Documents/upgrade-projects/hk-aws-agt-rpt-admin-sws/node_modules/@angular-builders/custom-webpack/dist/dev-server/index.js
- /Users/alexawu/Documents/upgrade-projects/hk-aws-agt-rpt-admin-sws/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /Users/alexawu/Documents/upgrade-projects/hk-aws-agt-rpt-admin-sws/node_modules/@angular-devkit/architect/node/index.js
- /Users/alexawu/Documents/upgrade-projects/hk-aws-agt-rpt-admin-sws/node_modules/@angular/cli/src/command-builder/architect-base-command-module.js
- /Users/alexawu/Documents/upgrade-projects/hk-aws-agt-rpt-admin-sws/node_modules/@angular/cli/src/command-builder/architect-command-module.js
- /Users/alexawu/Documents/upgrade-projects/hk-aws-agt-rpt-admin-sws/node_modules/@angular/cli/src/commands/serve/cli.js
- /Users/alexawu/Documents/upgrade-projects/hk-aws-agt-rpt-admin-sws/node_modules/@angular/cli/src/commands/command-config.js
- /Users/alexawu/Documents/upgrade-projects/hk-aws-agt-rpt-admin-sws/node_modules/@angular/cli/src/command-builder/command-runner.js
- /Users/alexawu/Documents/upgrade-projects/hk-aws-agt-rpt-admin-sws/node_modules/@angular/cli/lib/cli/index.js
- /Users/alexawu/Documents/upgrade-projects/hk-aws-agt-rpt-admin-sws/node_modules/@angular/cli/lib/init.js
See "/private/var/folders/hz/c6mk40394n57p3y5090264w83xhtk8/T/ng-KCoLJA/angular-errors.log" for further details.

And here is my package.json:
 "dependencies": {
    "@angular-builders/custom-webpack": "^17.0.0",
    "@angular/animations": "^17.0.8",
    "@angular/cdk": "^17.0.4",
    "@angular/common": "^17.0.8",
    "@angular/compiler": "^17.0.8",
    "@angular/core": "^17.0.8",
    "@angular/forms": "^17.0.8",
    "@angular/platform-browser": "^17.0.8",
    "@angular/platform-browser-dynamic": "^17.0.8",
    "@angular/router": "^17.0.8",
    "@manulife-design/md": "^1.0.5",
    "file-saver": "^2.0.5",
    "numeral": "^2.0.6",
    "powerbi-client-angular": "^3.0.5",
    "rxjs": "~7.8.1",
    "single-spa": "^5.9.5",
    "single-spa-angular": "github:single-spa/single-spa-angular#ng17",
    "tslib": "^2.1.0",
    "xlsx": "^0.18.5",
    "zone.js": "^0.14.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^17.0.8",
    "@angular/cli": "^17.0.8",
    "@angular/compiler-cli": "^17.0.8",
    "@angular/language-service": "^17.0.8",
    "@types/file-saver": "^2.0.4",
    "@types/jasmine": "^4.3.5",
    "@types/jasminewd2": "~2.0.10",
    "@types/node": "~16.11.7",
    "codelyzer": "^6.0.2",
    "jasmine-core": "~4.6.0",
    "jasmine-spec-reporter": "~7.0.0",
    "karma": "~6.4.2",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage-istanbul-reporter": "~3.0.3",
    "karma-jasmine": "^5.1.0",
    "karma-jasmine-html-reporter": "^2.0.0",
    "protractor": "~7.0.0",
    "sonar-scanner": "^3.1.0",
    "systemjs-webpack-interop": "^2.3.7",
    "ts-node": "~10.9.1",
    "tslint": "~6.1.3",
    "typescript": "^5.2.2",
    "webpack": "^5.88.2"
  }

**Comment by arturovt** [comment]
Why would you use the ng17 branch?

**Comment by Wushurui** [comment]
@arturovt Because our project uses Angular17, but single-spa-angular does not yet support the angular17 version, but I saw the commit you mentioned, so I want to try it with your ng17 branch.

**Comment by arturovt** [comment]
The single-spa-angular is compatible with angular 17.

**Comment by Wushurui** [comment]
OK, thanks

**Comment by b-ferrari** [comment]
@arturovt - Is there anything I can do to help bump this merge along? I'm sure you're super busy, but this has been open for a few months now and I figured it wouldn't hurt to merge it in before angular 18 rolls around 😄

**Comment by roshaw** [comment]
I see that all changes about ng17 are inside the main branch. Is there a plan to relase npm version?

**Pull request merged**
