### PR TITLE
feat: create v5 update schematic

### PR DESCRIPTION
**Pull request by manbearwiz**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Feature

## What is the current behavior?

Users need to fix a breaking change when upgrading to `single-spa-angular@^5` manually.

Issue Number: #455

## What is the new behavior?

Running `ng update single-spa-angular@5` removes `AnimationEngine` and automatically fixes https://github.com/single-spa/single-spa-angular/pull/362#discussion_r640970908.

## Does this PR introduce a breaking change?

- [x] No

### CODE REVIEW

**Comment by arturovt** [comment]
Could you please not move files around (e.g. test-utils)? This will reduce the number of changed files.

Also, the CI is failing.

**Comment by manbearwiz** [comment]
I had moved the test utils because it felt weird to have the new update schematic import from the inside the add schematic directory. I reverted that now though. Not sure why CI is failing. Jest passes on 2 different machines on my end. I removed the silent flag for now to hopefully see a more useful message.

**Comment by manbearwiz** [comment]
That resolved it. Ill remove the diagnostics and rebase.

**Comment by manbearwiz** [comment]
@arturovt how do you want to release this? alpha version first to validate or minor release right away?

**Pull request merged**
