### PR TITLE
fix: add webpack to package `exports`

### PR DESCRIPTION
**Pull request by arturovt**

### CODE REVIEW

**Comment by Den-dp** [comment]
This fix works for me 👍

**Comment by rahulvchandwani** [comment]
@joeldenning This works for me too. Please merge the PR.

**Review by jogelin — APPROVED** [review]

**Comment by murugan1992info** [comment]
Manually added changes in single-spa-angular/package.json  and  webpack issue seems to be resolved I guess.  But After that another error popped out, PFB for error message

image

 Do we have stable version combination for Angular 13 with single-spa-angular ?

**Comment by jogelin** [comment]
> Manually added changes in single-spa-angular/package.json and webpack issue seems to be resolved I guess. But After that another error popped out, PFB for error message
> 
> image
> 
> Do we have stable version combination for Angular 13 with single-spa-angular ?

This is working fine for me, did you have a look [at my last comment](https://github.com/single-spa/single-spa-angular/issues/395#issuecomment-1027930146)?

**Review by Den-dp — APPROVED** [review]

**Review by rahulvchandwani — APPROVED** [review]

**Review by lobinhojr — APPROVED** [review]

**Comment by lobinhojr** [comment]
@joeldenning 🆙

**Comment by justrhysism** [comment]
@arturovt would it be worth also exporting the types?

```json
    "./lib/webpack": {
      "types": "./lib/webpack/index.d.ts",
      "default": "./lib/webpack/index.js"
    }
```

**Pull request merged**
