### PR TITLE
fix: support the Angular 10 comments in the tsconfig file (fixes #249)

### LINKED ISSUE #249: `ng add single-spa-angular@4` fails on fresh angular@10 project
### Demonstration
```
> npm i -g @angular/cli@10.0.3
> ng new ngcli1003
> cd .\ngcli1003\
```
```
> ng add single-spa-angular@4
Package has unmet peer dependencies. Adding the package may not succeed.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
? Does your application use Angular routing? Yes
? Does your application use BrowserAnimationsModule? Yes
    Added 'single-spa' as a dependency
    Added 'single-spa-angular' as a dependency
    Added '@angular-builders/custom-webpack' as a dependency
    Generated 'main.single-spa.ts
    Generated 'single-spa-props.ts
    Generated asset-url.ts
    Generated extra-webpack.config.js
    Using @angular-devkit/custom-webpack builder.
Unexpected token / in JSON at position 0
```

### Expected Behavior
`ng add single-spa-angular@4` should work for fresh project generated via @angular/cli@10

### Actual Behavior
`ng add single-spa-angular@4` fails with the following error:
```
Unexpected token / in JSON at position 0
```

----

After some debugging, I found that it fails while parsing the tsconfig
https://github.com/single-spa/single-spa-angular/blob/cc96477d0f526a61c6603a535a0d4b07741a416c/schematics/ng-add/index.ts#L159-L167
just because all tsconfig's in @angular@10 project contains `/* comments */`.
```
> cat .\tsconfig.app.json
/* To learn more about this file see: https://angular.io/config/tsconfig. */
{
  "extends": "./tsconfig.base.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app",
    "types": []
  },
  "files": [
    "src/main.ts",
    "src/polyfills.ts"
  ],
  "include": [
    "src/**/*.d.ts"
  ]
}
```
tsconfig is json5 so comments are a valid thing https://github.com/json5/json5#comments

This is another piece that would be nice to resolve in order to fully support #232

### PR DESCRIPTION
**Pull request by celian-garcia**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #249 
The schematic doesn't manage to parse the tsconfig with comments.

## What is the new behavior?
Comments in tsconfig are ignored.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by celian-garcia** [comment]
I noticed the check failing and working on it. BTW awesome work on the CI/CD ! it is really reassuring to have so much tests around us.

**Comment by joeldenning** [comment]
The tests are failing - is that related to your changes here?

**Comment by celian-garcia** [comment]
It appears to not be related yeah but tomorrow I have time to run the cypress tests locally. Moreover I modified a bit my code today locally because it sounded weird to me the if else. So anyway you can expect a new commit tomorrow amending this one. Good evening !

**Comment by celian-garcia** [comment]
I updated the PR with a more natural if else in the 'files' field replacement script.
Updated as well the jest test for this part to be more angular clish.

It is a bit verbose... actually they have a json-file utils less verbose which is not exposed unfortunately ! 
https://github.com/angular/angular-cli/blob/master/packages/schematics/angular/utility/json-file.ts 😢 

### About the cypress tests.
Running them locally, it appeared to me that they are not that stable. I ran them 3 times and it failed one time. I suspect that sometimes, the start of the integration app can take a bit more time than an instant and cypress run on something that is not properly loaded. A simple wait would solve probably the issue... Or is there more intelligent behaviours in cypress with active wait ?

**Comment by joeldenning** [comment]
Published in https://github.com/single-spa/single-spa-angular/releases/tag/v4.3.2. The publish flow went a bit weird so I'm not sure I did it right. Let me know if 4.3.2 works for you.

**Comment by celian-garcia** [comment]
The only thing I can tell you is that I received a notification from renovate bot to update the version to 4.3.2 ^^ this bot is awesome. I can't tell you more for now because I am in vacation. 

Moreover, before to go I tested the schematic using yarn link and it worked perfectly.

**Pull request merged**
